CREDS:
    GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    APP_CRED: ${APP_CRED}
MODEL:
    MODEL_NAME: gemini-2.5-flash
    EMBEDDING_MODEL_NAME: ${EMBEDDING_MODEL_NAME}
GCP:
    GCP_PROJECT_ID: ${GCP_PROJECT_ID}
    BUCKET_NAME: ${BUCKET_NAME}
    FOLDER_NAME: ${FOLDER_NAME}
    CHROMA_COLL_NAME: collection
    CHROMA_PERSIST_DIR: ./chroma_langchain_db